package: uri-one
source: uri-one
version: '1:0.0.1'
architecture:
  - 386
  - amd64
  - arm
  - arm64
maintainer: DewepOnline <deb@dewep.online>
homepage: https://dewep.online/uri-one.html
description:
  - Link shortening service
section: web
priority: optional
control:
  depends:
    - systemd
    - ca-certificates
  build: scripts/build.sh
  conffiles:
    - /etc/uri-one/config.yaml
  preinst: scripts/preinst.sh
  postinst: scripts/postinst.sh
  prerm: scripts/prerm.sh
  postrm: scripts/postrm.sh
data:
  usr/bin/uri-one: build/bin/uri-one_%arch%
  etc/uri-one/config.yaml: configs/config.yaml
  etc/systemd/system/uri-one.service: init/systemd/uri-one.service 
