package: urione
source: urione
version: 1:1.4.0
architecture:
    - amd64
    - arm64
maintainer: The OSSPkg Team <github@osspkg.com>
homepage: https://uri.one/
description:
    - Link shortening service
section: utils
priority: optional
control:
    depends:
        - systemd
        - ca-certificates
    build: goppy build --arch=%arch%
    conffiles:
        - /etc/urione/config.yaml
    preinst: scripts/preinst.sh
    postinst: scripts/postinst.sh
    prerm: scripts/prerm.sh
    postrm: scripts/postrm.sh
data:
    bin/urione: build/urione_%arch%
    etc/urione/config.yaml: config/config.yaml
    var/log/urione.log: +empty
    etc/systemd/system/urione.service: init/urione.service
    var/lib/urione/migrations/202501040000_shorten_url.sql: migrations/202501040000_shorten_url.sql
