version: '2.4'

networks:
  urione-net:
    driver: bridge

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '0000'
      MYSQL_USER: 'test'
      MYSQL_PASSWORD: 'test'
      MYSQL_DATABASE: 'test_database'
    ports:
      - "127.0.0.1:3306:3306"
    networks:
      - urione-net
    healthcheck:
      test: [ "CMD", "mysql", "--user=root", "--password=0000", "-e", "SHOW DATABASES;" ]
      interval: 15s
      timeout: 30s
      retries: 30

  adminer:
    image: adminer:latest
    restart: always
    depends_on:
      - db
    ports:
      - "127.0.0.1:8090:8080"
    networks:
      - urione-net