env: prod

log:
  file_path: /var/log/urione.log
  format: syslog
  level: 4

http:
  - addr: 0.0.0.0:8080
    tag: main

mysql:
  - tags: master,slave
    host: 127.0.0.1
    port: 3306
    user: test
    password: test
    schema: test_database
    charset: utf8mb4
    collation: utf8mb4_unicode_ci
    timezone: UTC

mysql_migrate:
  - tags: master
    dir: /var/lib/urione/migrations

contacts:
  address: 'http://localhost:8080'
  org_name: 'Example Team'
  service_name: 'Shorten'
  email: 'help@example.com'

captcha:
  use: false
  client_key: 'ysc1_************************************************'
  server_key: 'ysc2_************************************************'
  validate_url: 'https://smartcaptcha.yandexcloud.net/validate'

exclude_domains:
  - localhost

shorten_alphabet: Gdr1Mq7p5ebLUhsIaBQVA3S8gmHjPDtC4ZWFRv6cnyKXiOwkf9zuoJlEYTx20N
