env: dev

log: /dev/stdout
level: 5

http:
  addr: 127.0.0.1:8888
debug:
  addr: 127.0.0.1:12080

middleware:
  throttling: 300

sqlite:
  - name: base
    file: /home/user/Документы/__dewep__/uri-one/db.sqlite3
